mysite/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'puntadelcielo'
urlpatterns = [
    path('', include('puntadelcielo.urls')),
]

puntadelcielo/urls.py
from django.urls import path

from . import views

app_name = 'puntadelcielo'
urlpatterns = [
    path('', views.index, name='index'),
    path('instalaciones/', views.facilities, name='facilities'),
    path('contacto/', views.contact, name='contact'),
    path('preguntas/', views.questions, name='questions'),
]

puntadelcielo/models/models.py
from django.db import models
from django.utils import timezone as tz

class WeatherRequest(models.Model):
    last_updated = models.DateTimeField()
    data = models.JSONField()
    @property
    def localtime(self):
        return tz.localtime(self.last_updated)
    def __str__(self):
        return f"({self.localtime})"

puntadelcielo/models/weatherMap.py
from .models import WeatherRequest  as WR
from django.utils import timezone as tz
from datetime import datetime as dt, timedelta
from .wind import Wind
import json
import requests
import pytz
import copy

# OPENWEATHER API = OWAPI
# DB = DATABASE

class WeatherMap:
    '''https://openweathermap.org/'''
    latitude = 20.4764322
    longitude = -97.006642
    appikey = "5af0042005116596d75564e0d405e625"
    request_dt : 'DateTimeLocale' = None
    data : 'Dict<any>' = None 

    def __init__(self):
        '''All datetime saved in the DB is in utc format and used in localtime format
            Datetime saved in memory is in localtime format   
        '''
        weather_reqs = WR.objects.all()
        if len( weather_reqs )== 0 :
            print("........WR first update........")
            # first request to api gets its datetime and data to be the first ones put into the DB
            wr = WR(last_updated = tz.now() )
            WeatherMap.request_dt = wr.localtime 
            WeatherMap.data = self.fetch_data()
            wr.data = json.dumps(WeatherMap.data)  
            wr.save()
        else :
            # if there is a date and data in the DB already then just assign them to the class variables
            WeatherMap.request_dt = weather_reqs[0].localtime
            WeatherMap.data = json.loads(weather_reqs[0].data) 
        self.curr_dt = tz.localtime(tz.now())

    def get_data(self) -> 'Dict<any>':    
        ''' Returns a dict with data fetched from OWAPI if the response was a 2xx status 
            If there is a difference of 1 h between last_updated from the DB and curr_dt from the client time, then
            it will fetch new data from OWAPI and will return a dict if the response is ok, otherwise an empty dict 
            if there was a bad response from OWAPI then there is an empty dict in data in the DB, so two scenarios:
                - time passed between calls is superior than 0.16667h=10min, reset_time_error, then new data from OWAPI is fetched again
                - time passed between calss is less than 10 min then no new fetch is done and an empty dict is returned
        '''
        diff = WeatherMap.delta_hours(self.curr_dt, self.request_dt)
        reset_time_error = 0.16667
        if  diff > 1.0 or ( len(self.data)==0 and diff > reset_time_error ):
            # if there is a difference between the date in the DB and the current client datetime > 1 h then
            # update datetime and data in the DB and in the class variable request_dt
            # or if there was a bad response from and there is a difference in 0.16667h = 10min
            # then try again sending a get request to openweather api OWAPI
            self.request_dt = self.curr_dt
            weather_req = WR.objects.all()[0]
            weather_req.last_updated = tz.now()
            self.data = self.fetch_data()
            weather_req.data = json.dumps(self.data)
            weather_req.save()
        data = copy.deepcopy(self.data)   
        for k,val in self.data.items():
            if k=="current":
                for k2,val2 in val.items():
                    if k2 == "sunset" or k2 == "sunrise" or k2 == "dt":
                        if k2 == "dt": data[k][k2] = dt.strptime( val2, "%Y-%m-%d %H:%M:%S")
                        else:  data[k][k2] = dt.strptime( val2, "%H:%M:%S").time()
                    if k2 == "wind_deg":
                        data[k]["wind_dir"] = Wind.wind_dir(val2) # it converts degrees into wind directions like N S E O
                    if k2 == "wind_speed":
                        data[k]["wind_scale"] = Wind.wind_scale(val2) # it converts wind speed into Beaufort scale
            if k=="daily":
                for i,day in enumerate(val):
                    for k2,val2 in day.items():
                        if k2 == "sunset" or k2 == "sunrise" or k2 == "dt":
                            if k2 == "dt": data[k][i][k2] = dt.strptime( val2, "%Y-%m-%d %H:%M:%S")
                            else:  data[k][i][k2] = dt.strptime( val2, "%H:%M:%S").time()
                        if k2 == "wind_deg":
                            data[k][i]["wind_dir"] = Wind.wind_dir(val2) # it converts degrees into wind directions like N S E O
                        if k2 == "wind_speed":
                            data[k][i]["wind_scale"] = Wind.wind_scale(val2) # it converts wind speed into Beaufort scale

        return data

    @staticmethod
    def delta_hours(new: 'datetime', old: 'datetime') -> 'f64':
        hours = (new - old).seconds / 3600.0
        return hours

    def fetch_data(self) -> 'Dict<any>':
        ''' It fetches data from OWAPI and returns a dict  
            If there is a bad response from OWAPI then the error is handled returning an empty dict
        '''
        print("........FETCHING NEW WEATHER DATA........")
        print("........NEW TIME FOR UPDATING........")
        url = f"https://api.openweathermap.org/data/2.5/onecall?lat={self.latitude}&lon={self.longitude}&exclude=hourly,minutely,alerts&lang=sp&units=metric&appid={self.appikey}"
        data = None 
        try:
            data = requests.get(url).json()
        except :
            data = dict()
            print("........There was a mistake with the get request to openweathermap api........")
            print("data = ",data)
            return data
        WeatherMap.transform(data)
        print(f">> {self.request_dt} | {data['current']['temp']}°C")
        return data

    @staticmethod
    def transform(data: '&mut Dict<any>'):
        ''' It converts timestamp digit points, that represent datetime in a format of seconds, into datetime type
            It makes the necessary unit convertions
        '''
        def unix_to_datetime(value: 'i32') -> 'datetime':
            datetime = dt.fromtimestamp(value)
            datetime = f"{datetime.year:02}-{datetime.month:02}-{datetime.day:02}T{datetime.hour:02}:{datetime.minute:02}:{datetime.second:02}"
            return datetime
        for k,val in data.items():
            if k=="current":
                for k2,val2 in val.items():
                    if k2 == "sunset" or k2 == "sunrise" or k2 == "dt":
                        res = unix_to_datetime(val2).split("T")
                        if k2 == "dt": data[k][k2] = " ".join(res)
                        else:  data[k][k2] = res[1]
                    if k2 == "wind_speed":
                        data[k][k2] *= 3.6 # to convert m/s to k/h
            if k=="daily":
                for i,day in enumerate(val):
                    for k2,val2 in day.items():
                        if k2 == "sunset" or k2 == "sunrise" or k2 == "dt":
                            res = unix_to_datetime(val2).split("T")
                            if k2 == "dt": data[k][i][k2] = " ".join(res)
                            else:  data[k][i][k2] = res[1]
                        if k2 == "wind_speed":
                            data[k][i][k2] *= 3.6 # to convert m/s to k/h
                        if k2 == "pop":
                            data[k][i][k2] *= 100 # to convert decimal probability to percentage

    def __str__(self):
        return f"request_dt:({self.request_dt}), curr_dt:({self.curr_dt})"

puntadelcielo/models/wind.py
class Wind:
    @staticmethod
    def wind_dir(degrees:'i32') -> "String":
        if degrees == 0 or degrees == 360:
            return "N"
        elif degrees == 45 :
            return "NE"
        elif degrees < 45 :
            return "NNE"
        elif degrees == 90 :
            return "E"
        elif degrees < 90 :
            return "ENE"
        elif degrees == 135 :
            return "SE"
        elif degrees < 135 :
            return "ESE"
        elif degrees == 180 :
            return "S"
        elif degrees < 180 :
            return "SSE"
        elif degrees == 225 :
            return "SO"
        elif degrees < 225 :
            return "SSO"
        elif degrees == 270 :
            return "O"
        elif degrees < 270 :
            return "OSO"
        elif degrees == 315 :
            return "NO"
        elif degrees < 315 :
            return "ONO"
        else:
            return "NNO"

    @staticmethod
    def wind_scale(wind:'i32') -> "String":
        ''' It gives the wind Beaufort scale'''
        if wind < 2 :
            return "Calmado(0)"
        elif wind <= 5:
            return "Aire ligero(1)"
        elif wind <= 11:
            return "Briza ligera(2)"
        elif wind <= 19:
            return "Briza suave(3)"
        elif wind <= 28:
            return "Briza moderada(4)"
        elif wind <= 38:
            return "Briza fresca(5)"
        elif wind <= 49:
            return "Briza fuerte(6)"
        elif wind <= 61:
            return "Cerca de Vendaval(7)"
        elif wind <= 74:
            return "Vendaval(8)"
        elif wind <= 88:
            return "Vendaval fuerte(9)"
        elif wind <= 102:
            return "Tormenta(10)"
        elif wind <= 117:
            return "Tormenta violenta(11)"
        else:
            return "Huracán(12)"

puntadelcielo/views/frontView.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from ..models.weatherMap import WeatherMap

def index(request):
    weather = WeatherMap()
    context = {
        "weather" : weather.get_data()
    }
    if request.method == "GET":
        #return render("index.html",context)
        return render(request,"puntadelcielo/index.html", context) 

def facilities(request):
    weather = WeatherMap()
    context = {
        "weather" : weather.get_data(),
        "pictures": [
            {
                "name": "pool.webp",
                "caption": "Piscina"
            },
            {
                "name": "room.webp",
                "caption": "Habitación vista 1"
            },
            {
                "name": "roomview2.webp",
                "caption": "Habitación vista 2"
            },
            {
                "name": "roomview3.webp",
                "caption": "Habitación vista 3"
            },
            {
                "name": "restroomview1.webp",
                "caption": "Baño vista 1"
            },
            {
                "name": "restroomview2.webp",
                "caption": "Baño vista 2"
            }
        ]
    }
    if request.method == "GET":
        return render(request,"puntadelcielo/facilities.html",context) 

def questions(request):
    weather = WeatherMap()
    context = {
        "weather" : weather.get_data(),
        "questions": [
            {
                "question":"¿Cuánto cuesta rentar una habitación?",
                "answer": "Precio esta entre los $550 y $650 dependiendo si es temporada turística alta o baja"
            },
            {
                "question":"¿Qué fecha es el festival del coco en Tecolutla?",
                "answer": "Finales de Febrero y principios de Marzo"
            },
            {
                "question":"¿Qué tan lejos queda la playa del hotel?",
                "answer": "Esta a 4 cuadras, o aproximadamente unos 4 minutos caminando"
            },
            {
                "question":"¿Qué tan lejos queda el río de las instalaciones?",
                "answer": "Se encuentra a 280 metros o 3 minutos a pie"
            }
        ]
    }
    if request.method == "GET":
        return render(request,"puntadelcielo/qa.html",context) 

def contact(request):
    weather = WeatherMap()
    context = {
        "weather" : weather.get_data()
    }
    if request.method == "GET":
        return render(request,"puntadelcielo/contact.html", context) 

puntadelcielo/templates/puntadelcielo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Hotel Punta del Cielo</title>
    <meta charset="utf-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/bulma/bulma-0.9.1/css/bulma.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/navigationBar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/currWeatherCard.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/weatherDayCard.css' %}">

    <!-- baseCss will be overriden by its css children  -->
    {% block baseCss %}{% endblock %}

    <script src="https://use.fontawesome.com/5520a791e7.js" async></script>
    <script src="{% static 'puntadelcielo/js/toogler_burger.js' %}" defer></script> 
    <script src="{% static 'puntadelcielo/js/base.js' %}" defer></script> 

    <!--  baseScript will be overriden by its scripts children -->
    {% block baseScript %}
        <script src="" defer></script> 
    {% endblock %}
</head>
<body>

<!--  prevent Flash of unstyled content (FOUC) in Firefox only  -->
<script>0</script>
<!-- navigation bar menu  -->
<section id="hotelNavBar">
    <div class="leftBlock">
        <div class="hotelLogo">
            <img src="{% static 'puntadelcielo/images/travel.webp' %}" width="45" height="40" title="Flaticon">
        </div>
        <div class="hotelName">
            <p>
            Hotel Punta del Cielo
            </p>
        </div>
    </div>
    <div class="middleBlock">
        {% if weather %}
        <div class="weatherFrame">
            <button onclick="getWeather()"  class="btnWeatherInfo button mt-4 is-info"/>
                <strong><p>Clima &thinsp;</p></strong><i class="fa fa-info-circle"></i>
            </button>
            <div class="summaryWeather">
                <img src="https://openweathermap.org/img/wn/{{weather.current.weather.0.icon}}@2x.png" alt="clima de tecolutla veracruz"/>   
                <p class="" >{{weather.current.temp}}°C</p>
            </div> 
        </div>
        {% endif %}
    </div>
    <div class="rightBlock">
        <div class="btnMenu">
            <span onclick="openNav()">
                <p>Menú &thinsp;&#9776;</p>
            </span>
        </div>
    </div>
</section>

<!-- weather modal information -->          

{% if weather %}
{% include 'puntadelcielo/weatherModal.html' %}
{% endif %}

<!-- navigation bar menu content overlay -->
<section>
    <div id="myNav" class="overlay">
        <div class="container">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <div class="overlay-content">
                <a class="has-text-weight-bold" href="{% url 'puntadelcielo:index' %}" onclick="closeNav()">
                    Principal
                </a>
                <a class="has-text-weight-bold" href="{% url 'puntadelcielo:index' %}#activities" onclick="closeNav()">
                    Actividades
                </a>
                <a class="has-text-weight-bold" href="{% url 'puntadelcielo:facilities' %}" onclick="closeNav()" >
                    Instalaciones
                </a>
                <a class="" href="{% url 'puntadelcielo:contact' %}" onclick="closeNav()">
                    <strong>Contacto</strong>
                </a>
                <a class="has-text-weight-bold" href="{% url 'puntadelcielo:questions' %}" onclick="closeNav()" >
                   FAQs 
                </a>
            </div>
        </div>
    </div>
</section>

<!--  baseContent will be overriden by its children form the navigation bar  -->
{% block baseContent %}
    I am here in the base content
{% endblock %}

<footer id="baseFooter" class="footer has-background-grey-light	 is-transparent" id="myfooter">
    <ul class="footerMenu">
        <li>
            <a href="{% url 'puntadelcielo:index' %}" >Principal</a>
        </li>
        <li>
            <a href="{% url 'puntadelcielo:index' %}#activities" >Actividades</a>
        </li>
        <li>
            <a href="{% url 'puntadelcielo:facilities' %}" >Instalaciones y servicios</a>
        </li>
        <li>
            <a href="{% url 'puntadelcielo:contact' %}" >Contacto y ubicación</a>
        </li>
        <li>
            <a href="{% url 'puntadelcielo:questions' %}" >Preguntas frecuentes</a>
        </li>
    </ul>
    <div class="reserveRights">
        <hr>
        <p>&#169;{% now "Y" %} Hotel Punta del Cielo. Todos los derechos reservados.</p>    
        <p>Avenida Hidalgo #51 Tecolutla, Veracruz.</p>
    </div>
</footer>


</body>

</html>

puntadelcielo/templates/puntadelcielo/contact.html
{% extends "puntadelcielo/base.html" %}
{% load static %}

{% block baseCss %}
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/contact.css' %}">
{% endblock  %}

{% block baseScript %}
    <script src="{% static 'puntadelcielo/js/contact.js' %}" async>
</script>
{% endblock  %}

{% block baseContent %}

<section class="section contact">
    <div class="wrapperL1">
        <div class="instructions">
            <h1 class="title">¿Cómo llego?</h1>
            <article class="media">
                <figure class="media-left">
                    <div class="image is-64x64">
                        <img src="{% static "puntadelcielo/icons/walking.png" %}">
                    </div>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p>Saliendo de la terminal de ADO tendrá enfrente a la calle Mariano Abasolo, caminar sobre ella, en dirección al faro de Tecolutla. Doblar a mano derecha en la calle Hermenegildo Galeana. Por esta calle caminar derecho tres cuadras y en la esquina entre la calle Miguel Hidalgo y Mariano Abasolo nos encontrarás.</p>
                    </div>
                </div>
            </article>
            <hr>
            <article class="media">
                <figure class="media-left">
                    <div class="image is-64x64">
                        <img src="{% static "puntadelcielo/icons/car.png" %}">
                    </div>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p>Entrando a Tecolutla seguir todo derecho hasta llegar a la calle Revolución que se encuentra a mano derecha. Seguir hasta llegar a la calle Hidalgo y doblar a la izquierda. Después, seguir todo derecho pasando por el parque y a final de la calle nos encontrarás en la esquina entre la calle Hidalgo y Hermenegildo Galeana.</p>
                    </div>
                </div>
            </article>
        </div>
        <div class="location card"  style="width:600px;">
            <div class="card-image" style="height:450px;">
                <iframe src="about:blank" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0" ></iframe> 
            </div>
            <div class="card-content has-background-primary has-text-light">
                <div class="content">
                    <p>Estamos cerca de todo lo que necesitas para una agradable estancia cerca de la playa.</p>
                    <p>Si google maps no carga refrescar la página <button class="button is-warning" onClick="window.location.reload();">Refrescar</button></p>
                </div>
            </div>
        </div>
        <div class="woodContainer">
            <h3 class="myTitle">Contactanos</h3>    
            <div class="subWrapper">
                <img class="whatsapp_icon" src="{% static 'puntadelcielo/icons/whatsapp.png' %}" alt="whatsapp icono"/>
                <p class="tel">7661006738</p>
                <img class="email_icon" src="{% static 'puntadelcielo/icons/gmail.png' %}" alt="email icono"/>
                <p class="mail">hotelpuntadelcielo@gmail.com</p>
            </div>
        </div>
    </div>
</section>

{% endblock  %}

puntadelcielo/templates/puntadelcielo/facilities.html
{% extends "puntadelcielo/base.html" %}
{% load static %}

{% block baseCss %}
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/carousel.css' %}">
{% endblock %}

{% block baseScript %}
    <script src="{% static 'puntadelcielo/js/carousel.js' %}" defer></script>
{% endblock %}

{% block baseContent %}

<section class="section ">
    <div class="container">
        <div class="woodContainer">
            <h1 class="myTitle">Nuestras instalaciones</h1>
            <p>Ven y disfruta con tu familia o amigos de una agradable estancia con nosotros</p>
            <p>Estamos perfectamente ubicados </p>

        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="pictureFrame">
            <div class="slideshow-container">
                {% for picture in pictures  %}
                <div class="mySlides fade">
                    <div class="numbertext">
                        <p>{{forloop.counter}} / {{pictures|length}}</p>
                    </div>
                    <figure class="image is-3by2">
                        <img class="" src="{% static 'puntadelcielo/images/'|add:picture.name  %}" loading="lazy">
                        <div class="block mt-3">
                            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                            <a class="next" onclick="plusSlides(1)">&#10095;</a>
                        </div>
                    </figure>
                    <div class="text_"><p>{{picture.caption}}</p></div>
                </div>
                {% endfor %}
                <div style="text-align:center" id="dotContainer">
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section has-background-grey-lighter">
    <div class="container">
        <p class="title">
            Estamos ubicados cerca de todo lo que necesitas para pasar un tiempo relajado y a gusto
        </p>
        <div class="tile is-ancestor">
            <div class="tile is-4 is-vertical is-parent">
                <div class="tile is-child box">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-3by2">
                                <img class="zoom" src="{% static 'puntadelcielo/images/downtown.webp' %}" alt="Placeholder image" loading="lazy">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <p>
                                    A unas escasas 3 cuadras esta el parque y el palacio municipal de Tecolutla, ideal para salir a caminar con la familia y amigos.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tile is-child box">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-3by2">
                                <img class="zoom" src="{% static 'puntadelcielo/images/down_to_the_beach.webp' %}" alt="Placeholder image" loading="lazy">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <p>
                                    La playa queda a menos de 4 cuadras, o aproximadamente unos 4 minutos caminando, puedes estar tranquilo teniendo las instalaciones del hotel y la playa a unos 400 metros de distancia.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tile is-parent">
                <div class="tile is-child box">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-3by2">
                                <img class="zoom" src="{% static 'puntadelcielo/images/beach_river.webp' %}" alt="Placeholder image" loading="lazy">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <p>
                                    Nuestra gran ubicación permite a nuestros clientes una distancia corta de recorrido a pie de los sitios más visitados del pueblo, con la playa a unos escasos 400 metros y el río atrás de nosotros a 280 metros o 3 minutos a pie, donde podrás gozar de la hermosa vista que el río de Tecolutla ofrece y/o tomar paseos guiados en lancha a los manglares.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>	
        </div>
    </div>
</section>

{% endblock  %}

puntadelcielo/templates/puntadelcielo/qa.html
{% extends "puntadelcielo/base.html" %}
{% load static %}

{% block baseCss %}
    <link rel="stylesheet" type="text/css" href="{% static 'puntadelcielo/css/qa.css' %}">
{% endblock %}

{% block baseScript %}
    <script src="{% static 'puntadelcielo/js/qa.js' %}" defer></script>
{% endblock %}

{% block baseContent %}

<div class="columns is-tablet my-5 mx-4">
    <div class="column" >
        <div class="woodContainer">
            <h3 class="myTitle">FAQs</h3>
            <p>
                Se incluyen preguntas comunes que muchos clientes nos han solicitado, esto para facilitar la comunicación contigo y puedas planear a gusto tus vacaciones con tiempo y a tu propio modo.
            </p>
        </div>
    </div>
    <div class="column mx-5" >
        <div class="container">
            {% for question in questions  %}
            <div class="slidedown my-3">
                <div class="slidedown-trigger py-2">
                    <div class="question has-background-info py-2 is-unselectable">
                        <p>
                        {{question.question}}
                        <span class="slidedown-icon">
                           &ensp;<i class="fa fa-angle-double-down"></i> 
                        </span>
                        </p>

                    </div>
                </div>
                <div class="slidedown-menu is-hidden" >
                    <div class="box my-2">
                        <p>{{question.answer}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock  %}